# Generated by Django 3.2.3 on 2021-06-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20210627_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default='b5235e82-90ff-45bd-a3ba-bb6c4d6757da', editable=False, primary_key=True, serialize=False),
        ),
    ]
