# Generated by Django 3.2.3 on 2021-06-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='id',
            field=models.UUIDField(default='7fc87d17-34ae-4c46-93cd-76ec8e161a4e', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default='8414d824-77ed-408d-8de3-86c01e457589', editable=False, primary_key=True, serialize=False),
        ),
    ]
