# Generated by Django 3.2.3 on 2021-06-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_auto_20210627_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
